const actionTypes = {
  START_APP: "START_APP",
  UPDATE_STATE_DATA: "UPDATE_STATE_DATA",
  CHOOSE_PLAN: "CHOOSE_PLAN",
  CHOOSE_PAYMENT_METHOD: "CHOOSE_PAYMENT_METHOD",
  SHOW_SUCCESS_BOX: "SHOW_SUCCESS_BOX"
};
export default actionTypes;
